name: Monitor Gist Changes
on:
 push:
   branches:
     - master
 schedule:
   - cron: '* * * * *'
jobs:
 check-for-changes:
   runs-on: ubuntu-latest
   steps:
     - name: Check for changes
       run: |
         curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/gists/ed11ee6a24d3e120d8d4a85c4964aa3c > gist.json
         jq '.updated_at' gist.json > updated_at.txt
         if ! diff -q updated_at.txt old_updated_at.txt; then
           echo "Gist has been updated."
           # Here you could trigger an external event that would start your other workflow
         fi
